# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-08 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Img',
            new_name='Article',
        ),
    ]
