# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-08 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0002_auto_20180908_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='img')),
                ('img_name', models.TextField(default='pics')),
                ('img_tags', models.TextField(default='tags')),
                ('img_uploader', models.TextField(default='0')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='img_name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='img_tags',
        ),
        migrations.RemoveField(
            model_name='article',
            name='img_uploader',
        ),
        migrations.RemoveField(
            model_name='article',
            name='img_url',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='content', verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='发表时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='title', max_length=256, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
